# MVS 3.0 - Nixpacks 설정 파일
# Railway 자동 빌드 시스템을 위한 최적화된 설정

[phases.setup]
# Node.js 런타임 및 필수 패키지 설치
nixPkgs = ["nodejs", "npm", "python3", "make", "gcc"]

[phases.install]
# 의존성 설치 명령어 (루트에서 실행)
cmds = [
  "npm ci --only=production",
  "cd msv-server && npm ci"
]

[phases.build]
# 빌드 명령어
cmds = [
  "cd msv-server && npm run build"
]

[start]
# 애플리케이션 시작 명령어
cmd = "cd msv-server && npx ts-node --transpile-only src/index.ts"

# 환경 변수 설정
[env]
NODE_ENV = "production"
PORT = "5000"
HTTPS = "false"

# 변수 설정
[variables]
NODE_ENV = "production"
