[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start:railway"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "$PORT"
CI = "false"