import React from 'react';
import { createRoot, Root } from 'react-dom/client';
import { ThemeProvider, CssBaseline } from '@mui/material';
import { Box } from '@mui/material';
import i18n from '../../locales/i18n';
import { theme } from '../../theme';
import PayslipContent, { type PayslipLabels, type PayslipCompanyInfo } from './PayslipContent';
import type { PayrollGridRow } from './payroll/payrollGridTypes';

/** A4 인쇄 여백 — 좌우상하 1cm */
const PDF_MARGIN_MM = 10;
const A4_WIDTH_MM = 210;
const A4_HEIGHT_MM = 297;

/** MUI md(900px) 이상 레이아웃과 동일하게 캡처 */
const PDF_CAPTURE_WIDTH_PX = 900;
const PDF_ROOT_ID = 'payslip-pdf-capture-root';

export function buildPayslipLabels(): PayslipLabels {
  const p = 'payrollManagement.payslip';
  return {
    title: i18n.t(`${p}.title`),
    payrollBadge: i18n.t(`${p}.payrollBadge`),
    salaryStatement: i18n.t(`${p}.salaryStatement`),
    companyName: i18n.t(`${p}.companyName`),
    companyContact: i18n.t(`${p}.companyContact`),
    employee: i18n.t(`${p}.employee`),
    name: i18n.t(`${p}.name`),
    empId: i18n.t(`${p}.empId`),
    birthDate: i18n.t(`${p}.birthDate`),
    department: i18n.t(`${p}.department`),
    position: i18n.t(`${p}.position`),
    designation: i18n.t(`${p}.designation`),
    email: i18n.t(`${p}.email`),
    period: i18n.t(`${p}.period`),
    workingMonth: i18n.t(`${p}.workingMonth`),
    statementDate: i18n.t(`${p}.statementDate`),
    paidDays: i18n.t(`${p}.paidDays`),
    dateOfJoin: i18n.t(`${p}.dateOfJoin`),
    totalDaysInMonth: i18n.t(`${p}.totalDaysInMonth`),
    unpaidLeave: i18n.t(`${p}.unpaidLeave`),
    daysWorked: i18n.t(`${p}.daysWorked`),
    grossPay: i18n.t(`${p}.grossPay`),
    deductions: i18n.t(`${p}.deductions`),
    totalDeductions: i18n.t(`${p}.totalDeductions`),
    earningsAndDeductions: i18n.t(`${p}.earningsAndDeductions`),
    earnings: i18n.t(`${p}.earnings`),
    employeeDeductions: i18n.t(`${p}.employeeDeductions`),
    netPay: i18n.t(`${p}.netPay`),
    basicSalary: i18n.t(`${p}.basicSalary`),
    houseRentAllowance: i18n.t(`${p}.houseRentAllowance`),
    otherAllowance: i18n.t(`${p}.otherAllowance`),
    totalSalary: i18n.t(`${p}.totalSalary`),
    dayOt: i18n.t(`${p}.dayOt`),
    nightOt: i18n.t(`${p}.nightOt`),
    otRate: i18n.t(`${p}.otRate`),
    extraAllowance: i18n.t(`${p}.extraAllowance`),
    sumTotal: i18n.t(`${p}.sumTotal`),
    grossSalary: i18n.t(`${p}.grossSalary`),
    tds: i18n.t(`${p}.tds`),
    deductMonth: i18n.t(`${p}.deductMonth`),
    bank: i18n.t(`${p}.bank`),
    account: i18n.t(`${p}.account`),
    ifsc: i18n.t(`${p}.ifsc`),
    pfEmployee: i18n.t(`${p}.pfEmployee`),
    esicEmployee: i18n.t(`${p}.esicEmployee`),
    pt: i18n.t(`${p}.pt`),
    bankSection: i18n.t(`${p}.bankSection`),
    amountInWords: i18n.t(`${p}.amountInWords`),
    autoGenerated: i18n.t(`${p}.autoGenerated`)
  };
}

function renderPayslipTree(row: PayrollGridRow, labels: PayslipLabels, companyInfo?: PayslipCompanyInfo | null) {
  return React.createElement(
    ThemeProvider,
    { theme },
    React.createElement(
      Box,
      { id: PDF_ROOT_ID, sx: { bgcolor: '#FFFFFF', width: `${PDF_CAPTURE_WIDTH_PX}px`, boxSizing: 'border-box' } },
      React.createElement(CssBaseline),
      React.createElement(PayslipContent, {
        row,
        labels,
        companyInfo,
        wide: true,
        forPdf: true,
        showTitle: false
      })
    )
  );
}

function fitImageToPrintArea(
  canvasWidth: number,
  canvasHeight: number,
  printWidthMm: number,
  printHeightMm: number
): { widthMm: number; heightMm: number } {
  if (canvasWidth <= 0 || canvasHeight <= 0) {
    return { widthMm: printWidthMm, heightMm: printHeightMm };
  }
  const aspect = canvasWidth / canvasHeight;
  let widthMm = printWidthMm;
  let heightMm = widthMm / aspect;
  if (heightMm > printHeightMm) {
    heightMm = printHeightMm;
    widthMm = heightMm * aspect;
  }
  return { widthMm, heightMm };
}

export async function generatePayslipPdfBlob(
  row: PayrollGridRow,
  companyInfo?: PayslipCompanyInfo | null
): Promise<Blob> {
  const labels = buildPayslipLabels();
  const container = document.createElement('div');
  container.style.position = 'fixed';
  container.style.left = '-12000px';
  container.style.top = '0';
  container.style.width = `${PDF_CAPTURE_WIDTH_PX}px`;
  container.style.zIndex = '-1';
  container.style.background = '#FFFFFF';
  document.body.appendChild(container);

  const root: Root = createRoot(container);
  root.render(renderPayslipTree(row, labels, companyInfo));

  await document.fonts.ready;
  await new Promise<void>((resolve) => setTimeout(resolve, 600));

  try {
    const [{ default: html2canvas }, { jsPDF }] = await Promise.all([
      import('html2canvas'),
      import('jspdf')
    ]);
    const target = document.getElementById(PDF_ROOT_ID) as HTMLElement | null;
    if (!target) {
      throw new Error('Payslip PDF capture root not found');
    }
    const canvas = await html2canvas(target, {
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: '#FFFFFF',
      width: PDF_CAPTURE_WIDTH_PX,
      windowWidth: PDF_CAPTURE_WIDTH_PX,
      scrollX: 0,
      scrollY: 0
    });

    const pdf = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' });
    const printWidthMm = A4_WIDTH_MM - PDF_MARGIN_MM * 2;
    const printHeightMm = A4_HEIGHT_MM - PDF_MARGIN_MM * 2;
    const { widthMm, heightMm } = fitImageToPrintArea(canvas.width, canvas.height, printWidthMm, printHeightMm);
    const x = PDF_MARGIN_MM + (printWidthMm - widthMm) / 2;
    const y = PDF_MARGIN_MM;
    const imgData = canvas.toDataURL('image/png', 0.92);

    pdf.addImage(imgData, 'PNG', x, y, widthMm, heightMm);

    return pdf.output('blob');
  } finally {
    root.unmount();
    document.body.removeChild(container);
  }
}

export function downloadPayslipPdf(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export async function payslipBlobToBase64(blob: Blob): Promise<string> {
  return new Promise((resolve, reject) => {
    const r = new FileReader();
    r.onloadend = () => {
      const s = String(r.result || '');
      const b64 = s.includes(',') ? s.split(',')[1] : s;
      resolve(b64);
    };
    r.onerror = () => reject(new Error('read failed'));
    r.readAsDataURL(blob);
  });
}
