import React from 'react';
import { Box, Typography } from '@mui/material';
import type { PayrollGridRow } from './payroll/payrollGridTypes';
import { formatOtHourDisplay } from './payroll/payrollGridUtils';
import { loadPayrollColumnPrefs } from './payroll/payrollColumnPrefs';
import { loadPayrollSalaryRatios } from './payroll/payrollSalaryRatios';
import { formatPositionLabel } from '../../utils/positionLabels';
import {
  mvsBodyCardSx,
  mvsBodyTableFrameSx,
  mvsBodyTableInsetSx,
  mvsInnerCardSx,
  mvsPageDescriptionSx,
  mvsPageTitleSx
} from '../../theme/mvsLayout';

export type PayslipLabels = {
  title: string;
  payrollBadge: string;
  salaryStatement: string;
  companyName: string;
  companyContact: string;
  employee: string;
  empId: string;
  name: string;
  birthDate: string;
  department: string;
  position: string;
  designation: string;
  email: string;
  period: string;
  workingMonth: string;
  statementDate: string;
  paidDays: string;
  dateOfJoin: string;
  totalDaysInMonth: string;
  unpaidLeave: string;
  daysWorked: string;
  grossPay: string;
  deductions: string;
  totalDeductions: string;
  earningsAndDeductions: string;
  earnings: string;
  employeeDeductions: string;
  netPay: string;
  basicSalary: string;
  houseRentAllowance: string;
  otherAllowance: string;
  foodAllowance: string;
  totalSalary: string;
  dayOt: string;
  otRate: string;
  extraAllowance: string;
  sumTotal: string;
  grossSalary: string;
  tds: string;
  deductMonth: string;
  bank: string;
  account: string;
  ifsc: string;
  pfEmployee: string;
  esicEmployee: string;
  pt: string;
  bankSection: string;
  amountInWords: string;
  autoGenerated: string;
};

export type PayslipCompanyInfo = {
  name?: string;
  address?: string;
  phone?: string;
  email?: string;
  /** data URL 또는 업로드 URL */
  logo?: string;
};

/** 회사 API/캐시 객체를 명세서용 정보로 변환 */
export function toPayslipCompanyInfo(company: any): PayslipCompanyInfo {
  const logoRaw = company?.company_logo ?? company?.logo ?? '';
  return {
    name: company?.name || '',
    address: company?.address || '',
    phone: company?.phone || company?.phone_number || '',
    email: company?.email || '',
    logo: typeof logoRaw === 'string' ? logoRaw.trim() : '',
  };
}

/** 회사별 명세서에서 선택 가능한 기본 헤더 배치 */
export type PayslipHeaderLayout = 'standard' | 'compact' | 'companyFirst';

/** 표시용 회사명 — Private Limited / Pvt Ltd 등 법적 접미사 제거 */
export function shortCompanyName(name?: string | null): string {
  return String(name || '')
    .replace(/\bprivate\s+limited\b\.?/gi, '')
    .replace(/\bpvt\.?\s*ltd\.?\b/gi, '')
    .replace(/\s{2,}/g, ' ')
    .replace(/[,\s]+$/g, '')
    .trim();
}

type Props = {
  row: PayrollGridRow;
  labels: PayslipLabels;
  companyInfo?: PayslipCompanyInfo | null;
  /** 회사별 상수 영역·커스텀 컬럼 설정을 읽기 위한 회사 ID */
  companyId?: string | number | null;
  showTitle?: boolean;
  wide?: boolean;
  /** PDF 캡처용 — 2열 레이아웃 강제 (스타일은 미리보기와 동일) */
  forPdf?: boolean;
  headerLayout?: PayslipHeaderLayout;
};

const INR = 'en-IN';
const MVS_ROW_BORDER = '#D1DAE4';

/** 객체/[object Object]는 빈 값으로 — 화면에 그대로 노출하지 않음 */
function displayText(value: unknown): string {
  if (value == null || value === '') return '';
  if (typeof value === 'object') {
    if (value instanceof Date && !Number.isNaN(value.getTime())) {
      return formatDateOnly(value);
    }
    return '';
  }
  const s = String(value).trim();
  if (!s || /^\[object\s+object\]$/i.test(s)) return '';
  return s;
}

/** 입사일 등 — YYYY-MM-DD만 */
function formatDateOnly(value: unknown): string {
  if (value == null || value === '') return '';
  if (value instanceof Date && !Number.isNaN(value.getTime())) {
    const y = value.getFullYear();
    const m = String(value.getMonth() + 1).padStart(2, '0');
    const d = String(value.getDate()).padStart(2, '0');
    return `${y}-${m}-${d}`;
  }
  if (typeof value === 'object') return '';
  const s = String(value).trim();
  if (!s || /^\[object\s+object\]$/i.test(s)) return '';
  const iso = s.match(/^(\d{4})[./-](\d{1,2})[./-](\d{1,2})/);
  if (iso) {
    return `${iso[1]}-${iso[2].padStart(2, '0')}-${iso[3].padStart(2, '0')}`;
  }
  const parsed = new Date(s);
  if (!Number.isNaN(parsed.getTime()) && (/\bGMT\b/i.test(s) || /[A-Za-z]{3}/.test(s))) {
    const y = parsed.getFullYear();
    const m = String(parsed.getMonth() + 1).padStart(2, '0');
    const d = String(parsed.getDate()).padStart(2, '0');
    return `${y}-${m}-${d}`;
  }
  return s;
}

function parseMoney(v: string | number | undefined | null): number {
  if (v === '' || v == null) return 0;
  if (typeof v === 'number') return Number.isFinite(v) ? v : 0;
  const n = parseFloat(String(v).replace(/,/g, '').trim());
  return Number.isFinite(n) ? n : 0;
}

/** 급여 명세서 금액 — 정수 내림 */
export function money(n: number): string {
  return `INR ${Math.floor(Number(n || 0)).toLocaleString(INR, { maximumFractionDigits: 0 })}`;
}

function moneyFromField(v: string | number | undefined | null): string {
  return money(parseMoney(v));
}

function statementDateFromPeriod(period: string): string {
  const p = displayText(period);
  if (!p || !/^\d{4}-\d{2}$/.test(p)) return '';
  const [y, m] = p.split('-').map(Number);
  const last = new Date(y, m, 0);
  return last.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
}

const BELOW_20 = [
  '',
  'One',
  'Two',
  'Three',
  'Four',
  'Five',
  'Six',
  'Seven',
  'Eight',
  'Nine',
  'Ten',
  'Eleven',
  'Twelve',
  'Thirteen',
  'Fourteen',
  'Fifteen',
  'Sixteen',
  'Seventeen',
  'Eighteen',
  'Nineteen'
];
const TENS = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];

function twoDigits(n: number): string {
  if (n < 20) return BELOW_20[n];
  const t = Math.floor(n / 10);
  const o = n % 10;
  return `${TENS[t]}${o ? `-${BELOW_20[o]}` : ''}`.trim();
}

function threeDigits(n: number): string {
  if (n === 0) return '';
  const h = Math.floor(n / 100);
  const rest = n % 100;
  if (h) return `${BELOW_20[h]} Hundred${rest ? ` and ${twoDigits(rest)}` : ''}`;
  return twoDigits(rest);
}

function inrWordsCore(n: number): string {
  if (n === 0) return '';
  const crore = Math.floor(n / 10000000);
  const lakh = Math.floor((n % 10000000) / 100000);
  const thousand = Math.floor((n % 100000) / 1000);
  const hundred = n % 1000;
  const parts: string[] = [];
  if (crore) parts.push(`${inrWordsCore(crore)} Crore`.trim());
  if (lakh) parts.push(`${twoDigits(lakh)} Lakh`);
  if (thousand) parts.push(`${twoDigits(thousand)} Thousand`);
  if (hundred) parts.push(threeDigits(hundred));
  return parts.join(' ').replace(/\s+/g, ' ').trim();
}

export function inrAmountInWords(amount: number): string {
  const n = Math.floor(Number(amount || 0));
  if (n === 0) return 'Zero Only';
  return `${inrWordsCore(n)} Only`;
}

function SectionHeading({ children, compact }: { children: React.ReactNode; compact?: boolean }) {
  return (
    <Typography
      sx={{
        fontWeight: 700,
        fontSize: compact ? '0.72rem' : '0.8125rem',
        letterSpacing: '0.06em',
        color: 'primary.main',
        mb: compact ? 0.75 : 1.5,
        textTransform: 'uppercase'
      }}
    >
      {children}
    </Typography>
  );
}

const USER_INPUT_COLOR = '#B91C1C';

function EmpField({
  label,
  value,
  link,
  highlight,
  dateOnly,
  compact
}: {
  label: string;
  value: unknown;
  link?: boolean;
  highlight?: boolean;
  dateOnly?: boolean;
  compact?: boolean;
}) {
  const text = dateOnly ? formatDateOnly(value) : displayText(value);
  if (!text) return null;
  return (
    <Box sx={{ py: compact ? 0.35 : 0.75 }}>
      <Typography
        variant="caption"
        color="text.secondary"
        sx={{ display: 'block', fontWeight: 600, mb: compact ? 0.15 : 0.35, fontSize: compact ? '0.65rem' : undefined }}
      >
        {label}
      </Typography>
      <Typography
        variant="body2"
        sx={{
          fontWeight: 600,
          color: highlight ? USER_INPUT_COLOR : link ? 'info.main' : 'text.primary',
          wordBreak: 'break-word',
          fontSize: compact ? '0.78rem' : undefined,
          lineHeight: compact ? 1.25 : undefined,
        }}
      >
        {text}
      </Typography>
    </Box>
  );
}

function LedgerRow({
  label,
  value,
  total,
  totalTone,
  isLast,
  highlight,
  compact
}: {
  label: string;
  value: string;
  total?: boolean;
  totalTone?: 'earn' | 'deduct';
  isLast?: boolean;
  highlight?: boolean;
  compact?: boolean;
}) {
  const earnTotal = total && totalTone === 'earn';
  const deductTotal = total && totalTone === 'deduct';
  const highlightColor = highlight ? USER_INPUT_COLOR : undefined;
  return (
    <Box
      sx={{
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: 1.5,
        px: compact ? 1.5 : 2,
        py: compact ? 0.7 : 1.25,
        minHeight: compact ? 34 : 44,
        borderBottom: isLast ? 'none' : `1px solid ${MVS_ROW_BORDER}`,
        bgcolor: earnTotal ? 'primary.50' : '#FFFFFF'
      }}
    >
      <Typography
        variant="body2"
        sx={{
          fontWeight: total ? 700 : 500,
          color: highlightColor ?? (earnTotal ? 'primary.main' : deductTotal ? 'warning.dark' : 'text.secondary'),
          fontSize: compact ? '0.75rem' : '0.8125rem',
          minWidth: 0,
          flex: 1,
          pr: 1,
        }}
      >
        {label}
      </Typography>
      <Typography
        variant="body2"
        sx={{
          fontWeight: total ? 700 : 600,
          fontVariantNumeric: 'tabular-nums',
          color: highlightColor ?? (earnTotal ? 'primary.main' : deductTotal ? 'warning.dark' : 'text.primary'),
          whiteSpace: 'nowrap',
          fontSize: compact ? '0.75rem' : '0.8125rem',
          textAlign: 'right',
          ml: 'auto',
          minWidth: compact ? '7.5rem' : '8.5rem',
          flexShrink: 0,
        }}
      >
        {value}
      </Typography>
    </Box>
  );
}

function LedgerSpacer({ isLast }: { isLast?: boolean }) {
  return (
    <Box
      sx={{
        minHeight: 44,
        borderBottom: isLast ? 'none' : `1px solid ${MVS_ROW_BORDER}`,
        bgcolor: '#FFFFFF'
      }}
    />
  );
}

function LedgerColumnHeader({ title }: { title: string }) {
  return (
    <Box
      sx={{
        px: 2,
        py: 1.25,
        bgcolor: '#F1F5F9',
        borderBottom: `1px solid ${MVS_ROW_BORDER}`,
        borderTop: '2px solid',
        borderTopColor: 'primary.main'
      }}
    >
      <Typography
        sx={{
          fontWeight: 600,
          fontSize: '0.8125rem',
          letterSpacing: '0.02em',
          color: '#475569',
          textTransform: 'uppercase'
        }}
      >
        {title}
      </Typography>
    </Box>
  );
}

type LedgerLine = { label: string; value: string; highlight?: boolean };

function EarningsDeductionsTable({
  labels,
  earningItems,
  deductionItems,
  grossPay,
  totalDeductions,
  forPdf
}: {
  labels: PayslipLabels;
  earningItems: LedgerLine[];
  deductionItems: LedgerLine[];
  grossPay: number;
  totalDeductions: number;
  forPdf?: boolean;
}) {
  const rowCount = Math.max(earningItems.length, deductionItems.length);
  const detailRows = Array.from({ length: rowCount }, (_, index) => ({
    earn: earningItems[index] ?? null,
    deduct: deductionItems[index] ?? null
  }));

  const gridColumns = forPdf ? '1fr 1px 1fr' : { xs: '1fr', md: '1fr 1px 1fr' };
  const dividerDisplay = forPdf ? 'block' : { xs: 'none', md: 'block' };

  return (
    <Box sx={{ ...mvsBodyTableFrameSx, mb: forPdf ? 1.5 : 2.5, overflow: 'hidden' }}>
      <Box sx={{ display: 'grid', gridTemplateColumns: gridColumns }}>
        <LedgerColumnHeader title={labels.earnings} />
        <Box sx={{ display: dividerDisplay, bgcolor: '#CBD5E1' }} />
        <LedgerColumnHeader title={labels.employeeDeductions} />
      </Box>

      {detailRows.map((line, index) => (
        <Box key={`ledger-${index}`} sx={{ display: 'grid', gridTemplateColumns: gridColumns }}>
          {line.earn ? (
            <LedgerRow
              label={line.earn.label}
              value={line.earn.value}
              highlight={line.earn.highlight}
              compact={forPdf}
            />
          ) : (
            <LedgerSpacer />
          )}
          <Box sx={{ display: dividerDisplay, bgcolor: '#CBD5E1' }} />
          {line.deduct ? (
            <LedgerRow label={line.deduct.label} value={line.deduct.value} compact={forPdf} />
          ) : (
            <LedgerSpacer />
          )}
        </Box>
      ))}

      <Box
        sx={{
          display: 'grid',
          gridTemplateColumns: gridColumns,
          borderTop: `1px solid ${MVS_ROW_BORDER}`
        }}
      >
        <LedgerRow
          label={labels.grossSalary}
          value={money(grossPay)}
          total
          totalTone="earn"
          isLast
          compact={forPdf}
        />
        <Box sx={{ display: dividerDisplay, bgcolor: '#CBD5E1' }} />
        <LedgerRow
          label={labels.totalDeductions}
          value={money(totalDeductions)}
          total
          totalTone="deduct"
          isLast
          compact={forPdf}
        />
      </Box>
    </Box>
  );
}

function PayslipHeader({
  labels,
  showTitle,
  employeeName,
  workingMonth,
  paidDays,
  companyName,
  companyContact,
  companyLogo,
  forPdf,
  layout = 'standard'
}: {
  labels: PayslipLabels;
  showTitle: boolean;
  employeeName: string;
  workingMonth: string;
  paidDays: string;
  companyName: string;
  companyContact: string;
  companyLogo?: string;
  forPdf?: boolean;
  layout?: PayslipHeaderLayout;
}) {
  const periodStats = [
    { label: labels.workingMonth, value: displayText(workingMonth) },
    { label: labels.paidDays, value: displayText(paidDays) }
  ].filter((item) => item.value);
  const logoSrc = String(companyLogo || '').trim();
  const showCompanyBlock = layout !== 'compact' && (companyName !== '—' || Boolean(logoSrc));

  return (
    <Box
      sx={{
        px: { xs: 2, sm: 2.5 },
        py: forPdf ? 1.5 : 2.5,
        bgcolor: '#F0F4F8',
        borderBottom: '1px solid #CBD5E1',
        borderTop: '3px solid',
        borderTopColor: 'primary.main'
      }}
    >
      <Box
        sx={{
          display: 'flex',
          flexDirection: forPdf ? 'row' : { xs: 'column', md: 'row' },
          alignItems: forPdf ? 'flex-start' : { md: 'flex-start' },
          justifyContent: 'space-between',
          gap: 2
        }}
      >
        <Box sx={{ flex: 1, minWidth: 0 }}>
          <Box
            order={layout === 'companyFirst' ? 2 : 1}
            component="span"
            sx={{
              display: 'inline-block',
              px: 1.25,
              py: 0.4,
              mb: 1,
              borderRadius: '6px',
              bgcolor: 'primary.50',
              color: 'primary.main',
              fontSize: '0.65rem',
              fontWeight: 700,
              letterSpacing: '0.14em'
            }}
          >
            {layout !== 'compact' ? labels.payrollBadge : ''}
          </Box>
          <Typography
            sx={{
              ...mvsPageTitleSx,
              fontSize: { xs: '1.2rem', sm: '1.35rem' },
              mb: employeeName ? 0.5 : 1.5,
              color: 'text.primary'
            }}
          >
            {showTitle ? labels.salaryStatement : labels.title}
          </Typography>
          {employeeName ? (
            <Typography
              sx={{
                fontWeight: 700,
                fontSize: forPdf ? '1.15rem' : { xs: '1.2rem', sm: '1.35rem' },
                color: 'text.primary',
                lineHeight: 1.25,
                mb: 1.5,
                letterSpacing: '-0.01em',
              }}
            >
              {employeeName}
            </Typography>
          ) : null}
          <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1.5 }}>
            {periodStats.map((item) => (
              <Box
                key={item.label}
                sx={{
                  ...mvsInnerCardSx,
                  py: 1.25,
                  px: 1.75,
                  minWidth: 116,
                  borderRadius: '8px',
                  overflow: 'hidden'
                }}
              >
                <Typography
                  variant="caption"
                  color="text.secondary"
                  sx={{ fontWeight: 600, display: 'block', mb: 0.35 }}
                >
                  {item.label}
                </Typography>
                <Typography sx={{ fontWeight: 700, fontSize: '1.2rem', color: 'primary.main', lineHeight: 1.1 }}>
                  {item.value || '—'}
                </Typography>
              </Box>
            ))}
          </Box>
        </Box>

        {showCompanyBlock ? (
          <Box
            order={layout === 'companyFirst' ? 1 : 2}
            sx={{
              ...mvsInnerCardSx,
              flex: forPdf ? '0 1 340px' : { md: '0 1 340px' },
              width: forPdf ? 'auto' : { xs: '100%', md: 'auto' },
              py: 1.5,
              px: 1.75,
              borderRadius: '8px',
              overflow: 'hidden'
            }}
          >
            {logoSrc ? (
              <Box
                sx={{
                  mb: companyName !== '—' || companyContact ? 1 : 0,
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'flex-start',
                  maxWidth: '100%',
                }}
              >
                <Box
                  component="img"
                  src={logoSrc}
                  alt={companyName !== '—' ? companyName : labels.companyName}
                  sx={{
                    maxHeight: forPdf ? 48 : 56,
                    maxWidth: forPdf ? 180 : 200,
                    width: 'auto',
                    height: 'auto',
                    objectFit: 'contain',
                    display: 'block',
                  }}
                />
              </Box>
            ) : null}
            <Typography variant="caption" color="text.secondary" sx={{ fontWeight: 600, display: 'block', mb: 0.5 }}>
              {labels.companyName}
            </Typography>
            {companyName !== '—' ? (
              <Typography sx={{ fontWeight: 700, fontSize: '0.9rem', lineHeight: 1.35, color: 'text.primary' }}>
                {companyName}
              </Typography>
            ) : null}
            {companyContact ? (
              <Typography sx={{ ...mvsPageDescriptionSx, fontSize: '0.72rem', mt: 0.5, lineHeight: 1.45 }}>
                {companyContact}
              </Typography>
            ) : null}
          </Box>
        ) : null}
      </Box>
    </Box>
  );
}

const PayslipContent = React.forwardRef<HTMLDivElement, Props>(function PayslipContent(
  {
    row,
    labels,
    companyInfo,
    companyId,
    showTitle = true,
    wide = false,
    forPdf = false,
    headerLayout = 'standard'
  },
  ref
) {
  const dayHours = parseMoney(row.day_ot_hour);
  const otRate = parseMoney(row.ot_rate);
  const otPayTotal = Math.floor(dayHours * otRate);

  const grossPay = parseMoney(row.sum_total);
  const pfEmp = parseMoney(row.pf_employee);
  const esicEmp = parseMoney(row.esic_employee);
  const tdsAmt = parseMoney(row.tds);
  const ptAmt = parseMoney(row.pt);
  const otherDeduct = Math.max(0, parseMoney(row.deduct_this_month) - (pfEmp + esicEmp + tdsAmt + ptAmt));
  const totalDeductions =
    parseMoney(row.deduct_this_month) > 0
      ? parseMoney(row.deduct_this_month)
      : pfEmp + esicEmp + tdsAmt + ptAmt + otherDeduct;
  const netPay = parseMoney(row.net_salary_payable);

  const dayOtLabel =
    dayHours > 0 ? `${labels.dayOt} (${formatOtHourDisplay(dayHours)}h)` : labels.dayOt;

  const companyName = shortCompanyName(companyInfo?.name) || '—';
  const companyContact = [companyInfo?.address, companyInfo?.phone, companyInfo?.email]
    .filter((x) => !!String(x || '').trim())
    .join(' · ');

  // 엑셀 등에서 넘어온 수당 행이 있으면 리스트(열) 그대로 표시
  const customLines = Array.isArray(row.payslip_earning_lines) ? row.payslip_earning_lines : [];
  const earningItems: LedgerLine[] = customLines.length
    ? customLines.map((line) => ({
        label: line.label,
        value: money(line.amount),
        highlight: line.highlight,
      }))
    : [
        ...(() => {
          const ratios = loadPayrollSalaryRatios(companyId);
          const lines = ratios.parts.map((part) => {
            let amount = 0;
            if (part.id === 'basic_salary') amount = Number(row.basic_salary) || 0;
            else if (part.id === 'house_rent_allowance') amount = Number(row.house_rent_allowance) || 0;
            else if (part.id === 'other_allowance') amount = Number(row.other_allowance) || 0;
            else amount = Number(row.constant_parts?.[part.id]) || 0;
            return { label: part.label, value: money(amount) };
          });
          // 설정에 없는 상수 항목도 금액이 있으면 누락 없이 표시
          const known = new Set(ratios.parts.map((p) => p.id));
          Object.entries(row.constant_parts || {}).forEach(([id, amount]) => {
            if (known.has(id) || !(Number(amount) > 0)) return;
            lines.push({ label: id.replace(/_/g, ' '), value: money(amount) });
          });
          return lines;
        })(),
        ...(Number(row.food_allowance) > 0
          ? [{ label: labels.foodAllowance, value: money(row.food_allowance) }]
          : []),
        ...(dayHours > 0
          ? [{ label: dayOtLabel, value: money(otPayTotal), highlight: true }]
          : dayHours === 0 && otPayTotal === 0
            ? [{ label: labels.dayOt, value: money(0), highlight: true }]
            : []),
        { label: labels.extraAllowance, value: money(row.transport_allowance), highlight: true },
        ...(() => {
          const prefs = loadPayrollColumnPrefs(companyId);
          return Object.entries(row.custom_allowances || {})
            .filter(([, amount]) => Number(amount) > 0)
            .map(([key, amount]) => {
              const label =
                prefs.customColumns.find((c) => c.id === key)?.label ||
                key.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
              return { label, value: money(amount), highlight: true };
            });
        })(),
      ];

  const deductionItems: LedgerLine[] = [
    { label: labels.pfEmployee, value: moneyFromField(row.pf_employee) },
    { label: labels.esicEmployee, value: moneyFromField(row.esic_employee) },
    { label: labels.pt, value: moneyFromField(row.pt) },
    { label: labels.tds, value: money(row.tds) }
  ];
  if (otherDeduct > 0) {
    deductionItems.push({ label: labels.deductMonth, value: money(otherDeduct) });
  }

  return (
    <Box
      ref={ref}
      sx={{
        bgcolor: forPdf ? '#FFFFFF' : 'bodyArea.main',
        color: 'text.primary',
        p: wide || forPdf ? 0 : { xs: 0, sm: 0.5 },
        width: wide || forPdf ? '100%' : undefined,
        maxWidth: wide || forPdf ? '100%' : 760,
        mx: wide || forPdf ? 0 : 'auto',
        boxSizing: 'border-box'
      }}
    >
      <Box sx={{ ...mvsBodyCardSx, overflow: 'hidden' }}>
        <PayslipHeader
          labels={labels}
          showTitle={showTitle}
          employeeName={displayText(row.employee_name)}
          workingMonth={displayText(row.working_month)}
          paidDays={displayText(row.days_worked)}
          companyName={companyName}
          companyContact={companyContact}
          companyLogo={companyInfo?.logo}
          forPdf={forPdf}
          layout={headerLayout}
        />

        <Box sx={{ px: { xs: 2, sm: 2.5 }, pb: forPdf ? 1.5 : 2.5, pt: forPdf ? 1.5 : 2.5 }}>
          {/* 직원 정보 — A4 한 페이지를 위해 3열 */}
          <SectionHeading compact={forPdf}>{labels.employee}</SectionHeading>
          <Box sx={{ ...mvsBodyTableInsetSx, mb: forPdf ? 1.5 : 3, borderRadius: '8px', overflow: 'hidden' }}>
            <Box
              sx={{
                ...mvsBodyTableFrameSx,
                p: forPdf ? 1.25 : { xs: 1.5, sm: 2 },
                display: 'grid',
                gridTemplateColumns: forPdf ? '1fr 1fr 1fr' : { xs: '1fr', sm: '1fr 1fr 1fr' },
                columnGap: forPdf ? 2 : 2.5,
                rowGap: 0
              }}
            >
              <EmpField compact={forPdf} label={labels.workingMonth} value={row.working_month} />
              <EmpField
                compact={forPdf}
                label={labels.statementDate}
                value={statementDateFromPeriod(displayText(row.working_month))}
              />
              <EmpField compact={forPdf} label={labels.totalDaysInMonth} value={row.total_day_of_month} />
              <EmpField compact={forPdf} label={labels.paidDays} value={row.days_worked} />
              <EmpField
                compact={forPdf}
                label={labels.unpaidLeave}
                value={displayText(row.unpaid_leave) || '0'}
                highlight
              />
              <EmpField compact={forPdf} label={labels.empId} value={row.emp_id} />
              <EmpField
                compact={forPdf}
                label={labels.designation}
                value={formatPositionLabel(row.position, 'en', false)}
              />
              <EmpField compact={forPdf} label={labels.email} value={row.employee_email} link />
              <EmpField compact={forPdf} label={labels.dateOfJoin} value={row.joining_date} dateOnly />
              <EmpField compact={forPdf} label={labels.department} value={row.department} />
              <EmpField compact={forPdf} label={labels.bank} value={row.bank_name} />
              <EmpField compact={forPdf} label={labels.account} value={row.bank_account} />
              <EmpField compact={forPdf} label={labels.ifsc} value={row.ifsc} />
            </Box>
          </Box>

          {/* 지급 · 공제 — 합계 행 정렬 */}
          <SectionHeading compact={forPdf}>{labels.earningsAndDeductions}</SectionHeading>
          <EarningsDeductionsTable
            labels={labels}
            earningItems={earningItems}
            deductionItems={deductionItems}
            grossPay={grossPay}
            totalDeductions={totalDeductions}
            forPdf={forPdf}
          />

          {/* 실수령 — Body 내부 카드 */}
          <Box
            sx={{
              ...mvsInnerCardSx,
              mb: forPdf ? 1 : 2,
              border: '2px solid',
              borderColor: 'primary.light',
              bgcolor: 'primary.50',
              borderRadius: '8px',
              overflow: 'hidden',
              py: forPdf ? 1.25 : undefined,
              px: forPdf ? 1.5 : undefined,
            }}
          >
            <Typography
              sx={{
                fontWeight: 700,
                color: 'primary.main',
                fontSize: forPdf ? '0.75rem' : '0.85rem',
                mb: 0.5,
              }}
            >
              {labels.netPay}
            </Typography>
            <Typography
              sx={{
                fontWeight: 700,
                fontSize: forPdf ? '1.45rem' : { xs: '1.65rem', sm: '1.9rem' },
                color: 'text.primary',
                fontVariantNumeric: 'tabular-nums',
                lineHeight: 1.15,
                mb: forPdf ? 0.5 : 1,
                letterSpacing: '-0.02em'
              }}
            >
              {money(netPay)}
            </Typography>
            <Typography
              sx={{
                ...mvsPageDescriptionSx,
                color: 'success.dark',
                fontWeight: 600,
                fontSize: forPdf ? '0.72rem' : undefined,
              }}
            >
              {labels.amountInWords}: {inrAmountInWords(netPay)}
            </Typography>
          </Box>

          <Typography
            variant="caption"
            sx={{
              ...mvsPageDescriptionSx,
              display: 'block',
              textAlign: 'center',
              fontSize: forPdf ? '0.65rem' : undefined,
            }}
          >
            {labels.autoGenerated}
          </Typography>
        </Box>
      </Box>
    </Box>
  );
});

export default PayslipContent;
