import React from 'react';
import { Box, Typography } from '@mui/material';
import type { PayrollGridRow } from './payroll/payrollGridTypes';
import { formatOtHourDisplay } from './payroll/payrollGridUtils';
import {
  mvsBodyCardSx,
  mvsBodyTableFrameSx,
  mvsBodyTableInsetSx,
  mvsInnerCardSx,
  mvsPageDescriptionSx,
  mvsPageTitleSx
} from '../../theme/mvsLayout';

export type PayslipLabels = {
  title: string;
  payrollBadge: string;
  salaryStatement: string;
  companyName: string;
  companyContact: string;
  employee: string;
  empId: string;
  name: string;
  birthDate: string;
  department: string;
  position: string;
  designation: string;
  email: string;
  period: string;
  workingMonth: string;
  statementDate: string;
  paidDays: string;
  dateOfJoin: string;
  totalDaysInMonth: string;
  unpaidLeave: string;
  daysWorked: string;
  grossPay: string;
  deductions: string;
  totalDeductions: string;
  earningsAndDeductions: string;
  earnings: string;
  employeeDeductions: string;
  netPay: string;
  basicSalary: string;
  houseRentAllowance: string;
  otherAllowance: string;
  totalSalary: string;
  dayOt: string;
  nightOt: string;
  otRate: string;
  extraAllowance: string;
  sumTotal: string;
  grossSalary: string;
  tds: string;
  deductMonth: string;
  bank: string;
  account: string;
  ifsc: string;
  pfEmployee: string;
  esicEmployee: string;
  pt: string;
  bankSection: string;
  amountInWords: string;
  autoGenerated: string;
};

export type PayslipCompanyInfo = {
  name?: string;
  address?: string;
  phone?: string;
  email?: string;
};

type Props = {
  row: PayrollGridRow;
  labels: PayslipLabels;
  companyInfo?: PayslipCompanyInfo | null;
  showTitle?: boolean;
  wide?: boolean;
  /** PDF 캡처용 — 2열 레이아웃 강제 (스타일은 미리보기와 동일) */
  forPdf?: boolean;
};

const INR = 'en-IN';
const MVS_ROW_BORDER = '#D1DAE4';

function parseMoney(v: string | number | undefined | null): number {
  if (v === '' || v == null) return 0;
  if (typeof v === 'number') return Number.isFinite(v) ? v : 0;
  const n = parseFloat(String(v).replace(/,/g, '').trim());
  return Number.isFinite(n) ? n : 0;
}

/** 급여 명세서 금액 — 정수 내림 */
export function money(n: number): string {
  return `INR ${Math.floor(Number(n || 0)).toLocaleString(INR, { maximumFractionDigits: 0 })}`;
}

function moneyFromField(v: string | number | undefined | null): string {
  return money(parseMoney(v));
}

function statementDateFromPeriod(period: string): string {
  if (!period || !/^\d{4}-\d{2}$/.test(period)) return '—';
  const [y, m] = period.split('-').map(Number);
  const last = new Date(y, m, 0);
  return last.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
}

const BELOW_20 = [
  '',
  'One',
  'Two',
  'Three',
  'Four',
  'Five',
  'Six',
  'Seven',
  'Eight',
  'Nine',
  'Ten',
  'Eleven',
  'Twelve',
  'Thirteen',
  'Fourteen',
  'Fifteen',
  'Sixteen',
  'Seventeen',
  'Eighteen',
  'Nineteen'
];
const TENS = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];

function twoDigits(n: number): string {
  if (n < 20) return BELOW_20[n];
  const t = Math.floor(n / 10);
  const o = n % 10;
  return `${TENS[t]}${o ? ` ${BELOW_20[o]}` : ''}`.trim();
}

function threeDigits(n: number): string {
  if (n === 0) return '';
  const h = Math.floor(n / 100);
  const rest = n % 100;
  if (h) return `${BELOW_20[h]} Hundred${rest ? ` ${twoDigits(rest)}` : ''}`;
  return twoDigits(rest);
}

function inrWordsCore(n: number): string {
  if (n === 0) return '';
  const crore = Math.floor(n / 10000000);
  const lakh = Math.floor((n % 10000000) / 100000);
  const thousand = Math.floor((n % 100000) / 1000);
  const hundred = n % 1000;
  const parts: string[] = [];
  if (crore) parts.push(`${inrWordsCore(crore)} Crore`.trim());
  if (lakh) parts.push(`${twoDigits(lakh)} Lakh`);
  if (thousand) parts.push(`${twoDigits(thousand)} Thousand`);
  if (hundred) parts.push(threeDigits(hundred));
  return parts.join(' ').replace(/\s+/g, ' ').trim();
}

export function inrAmountInWords(amount: number): string {
  const n = Math.floor(Number(amount || 0));
  if (n === 0) return 'Zero Only';
  return `${inrWordsCore(n)} Only`;
}

function SectionHeading({ children }: { children: React.ReactNode }) {
  return (
    <Typography
      sx={{
        fontWeight: 700,
        fontSize: '0.8125rem',
        letterSpacing: '0.06em',
        color: 'primary.main',
        mb: 1.5,
        textTransform: 'uppercase'
      }}
    >
      {children}
    </Typography>
  );
}

const USER_INPUT_COLOR = '#B91C1C';

function EmpField({
  label,
  value,
  link,
  highlight
}: {
  label: string;
  value: string;
  link?: boolean;
  highlight?: boolean;
}) {
  return (
    <Box sx={{ py: 0.75 }}>
      <Typography variant="caption" color="text.secondary" sx={{ display: 'block', fontWeight: 600, mb: 0.35 }}>
        {label}
      </Typography>
      <Typography
        variant="body2"
        sx={{
          fontWeight: 600,
          color: highlight ? USER_INPUT_COLOR : link ? 'info.main' : 'text.primary',
          wordBreak: 'break-word'
        }}
      >
        {value || '—'}
      </Typography>
    </Box>
  );
}

function LedgerRow({
  label,
  value,
  total,
  totalTone,
  isLast,
  highlight
}: {
  label: string;
  value: string;
  total?: boolean;
  totalTone?: 'earn' | 'deduct';
  isLast?: boolean;
  highlight?: boolean;
}) {
  const earnTotal = total && totalTone === 'earn';
  const deductTotal = total && totalTone === 'deduct';
  const highlightColor = highlight ? USER_INPUT_COLOR : undefined;
  return (
    <Box
      sx={{
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: 1.5,
        px: 2,
        py: 1.25,
        minHeight: 44,
        borderBottom: isLast ? 'none' : `1px solid ${MVS_ROW_BORDER}`,
        bgcolor: earnTotal ? 'primary.50' : '#FFFFFF'
      }}
    >
      <Typography
        variant="body2"
        sx={{
          fontWeight: total ? 700 : 500,
          color: highlightColor ?? (earnTotal ? 'primary.main' : deductTotal ? 'warning.dark' : 'text.secondary'),
          fontSize: '0.8125rem'
        }}
      >
        {label}
      </Typography>
      <Typography
        variant="body2"
        sx={{
          fontWeight: total ? 700 : 600,
          fontVariantNumeric: 'tabular-nums',
          color: highlightColor ?? (earnTotal ? 'primary.main' : deductTotal ? 'warning.dark' : 'text.primary'),
          whiteSpace: 'nowrap',
          fontSize: '0.8125rem'
        }}
      >
        {value}
      </Typography>
    </Box>
  );
}

function LedgerSpacer({ isLast }: { isLast?: boolean }) {
  return (
    <Box
      sx={{
        minHeight: 44,
        borderBottom: isLast ? 'none' : `1px solid ${MVS_ROW_BORDER}`,
        bgcolor: '#FFFFFF'
      }}
    />
  );
}

function LedgerColumnHeader({ title }: { title: string }) {
  return (
    <Box
      sx={{
        px: 2,
        py: 1.25,
        bgcolor: '#F1F5F9',
        borderBottom: `1px solid ${MVS_ROW_BORDER}`,
        borderTop: '2px solid',
        borderTopColor: 'primary.main'
      }}
    >
      <Typography
        sx={{
          fontWeight: 600,
          fontSize: '0.8125rem',
          letterSpacing: '0.02em',
          color: '#475569',
          textTransform: 'uppercase'
        }}
      >
        {title}
      </Typography>
    </Box>
  );
}

type LedgerLine = { label: string; value: string; highlight?: boolean };

function EarningsDeductionsTable({
  labels,
  earningItems,
  deductionItems,
  grossPay,
  totalDeductions,
  forPdf
}: {
  labels: PayslipLabels;
  earningItems: LedgerLine[];
  deductionItems: LedgerLine[];
  grossPay: number;
  totalDeductions: number;
  forPdf?: boolean;
}) {
  const rowCount = Math.max(earningItems.length, deductionItems.length);
  const detailRows = Array.from({ length: rowCount }, (_, index) => ({
    earn: earningItems[index] ?? null,
    deduct: deductionItems[index] ?? null
  }));

  const gridColumns = forPdf ? '1fr 1px 1fr' : { xs: '1fr', md: '1fr 1px 1fr' };
  const dividerDisplay = forPdf ? 'block' : { xs: 'none', md: 'block' };

  return (
    <Box sx={{ ...mvsBodyTableFrameSx, mb: 2.5, overflow: 'hidden' }}>
      <Box sx={{ display: 'grid', gridTemplateColumns: gridColumns }}>
        <LedgerColumnHeader title={labels.earnings} />
        <Box sx={{ display: dividerDisplay, bgcolor: '#C5CED9' }} />
        <LedgerColumnHeader title={labels.employeeDeductions} />
      </Box>

      {detailRows.map((line, index) => (
        <Box key={`ledger-${index}`} sx={{ display: 'grid', gridTemplateColumns: gridColumns }}>
          {line.earn ? (
            <LedgerRow
              label={line.earn.label}
              value={line.earn.value}
              highlight={line.earn.highlight}
            />
          ) : (
            <LedgerSpacer />
          )}
          <Box sx={{ display: dividerDisplay, bgcolor: '#C5CED9' }} />
          {line.deduct ? (
            <LedgerRow label={line.deduct.label} value={line.deduct.value} />
          ) : (
            <LedgerSpacer />
          )}
        </Box>
      ))}

      <Box
        sx={{
          display: 'grid',
          gridTemplateColumns: gridColumns,
          borderTop: `1px solid ${MVS_ROW_BORDER}`
        }}
      >
        <LedgerRow
          label={labels.grossSalary}
          value={money(grossPay)}
          total
          totalTone="earn"
          isLast
        />
        <Box sx={{ display: dividerDisplay, bgcolor: '#C5CED9' }} />
        <LedgerRow
          label={labels.totalDeductions}
          value={money(totalDeductions)}
          total
          totalTone="deduct"
          isLast
        />
      </Box>
    </Box>
  );
}

function PayslipHeader({
  labels,
  showTitle,
  workingMonth,
  paidDays,
  companyName,
  companyContact,
  forPdf
}: {
  labels: PayslipLabels;
  showTitle: boolean;
  workingMonth: string;
  paidDays: string;
  companyName: string;
  companyContact: string;
  forPdf?: boolean;
}) {
  const periodStats = [
    { label: labels.workingMonth, value: workingMonth },
    { label: labels.paidDays, value: paidDays }
  ];

  return (
    <Box
      sx={{
        px: { xs: 2, sm: 2.5 },
        py: 2.5,
        bgcolor: '#F0F4F8',
        borderBottom: '1px solid #C5CED9',
        borderTop: '3px solid',
        borderTopColor: 'primary.main'
      }}
    >
      <Box
        sx={{
          display: 'flex',
          flexDirection: forPdf ? 'row' : { xs: 'column', md: 'row' },
          alignItems: forPdf ? 'flex-start' : { md: 'flex-start' },
          justifyContent: 'space-between',
          gap: 2
        }}
      >
        <Box sx={{ flex: 1, minWidth: 0 }}>
          <Box
            component="span"
            sx={{
              display: 'inline-block',
              px: 1.25,
              py: 0.4,
              mb: 1,
              borderRadius: '6px',
              bgcolor: 'primary.50',
              color: 'primary.main',
              fontSize: '0.65rem',
              fontWeight: 700,
              letterSpacing: '0.14em'
            }}
          >
            {labels.payrollBadge}
          </Box>
          <Typography
            sx={{
              ...mvsPageTitleSx,
              fontSize: { xs: '1.2rem', sm: '1.35rem' },
              mb: 1.5,
              color: 'text.primary'
            }}
          >
            {showTitle ? labels.salaryStatement : labels.title}
          </Typography>
          <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1.5 }}>
            {periodStats.map((item) => (
              <Box
                key={item.label}
                sx={{
                  ...mvsInnerCardSx,
                  py: 1.25,
                  px: 1.75,
                  minWidth: 116,
                  borderRadius: '12px',
                  overflow: 'hidden'
                }}
              >
                <Typography
                  variant="caption"
                  color="text.secondary"
                  sx={{ fontWeight: 600, display: 'block', mb: 0.35 }}
                >
                  {item.label}
                </Typography>
                <Typography sx={{ fontWeight: 700, fontSize: '1.2rem', color: 'primary.main', lineHeight: 1.1 }}>
                  {item.value || '—'}
                </Typography>
              </Box>
            ))}
          </Box>
        </Box>

        {companyName !== '—' ? (
          <Box
            sx={{
              ...mvsInnerCardSx,
              flex: forPdf ? '0 1 340px' : { md: '0 1 340px' },
              width: forPdf ? 'auto' : { xs: '100%', md: 'auto' },
              py: 1.5,
              px: 1.75,
              borderRadius: '12px',
              overflow: 'hidden'
            }}
          >
            <Typography variant="caption" color="text.secondary" sx={{ fontWeight: 600, display: 'block', mb: 0.5 }}>
              {labels.companyName}
            </Typography>
            <Typography sx={{ fontWeight: 700, fontSize: '0.9rem', lineHeight: 1.35, color: 'text.primary' }}>
              {companyName}
            </Typography>
            {companyContact ? (
              <Typography sx={{ ...mvsPageDescriptionSx, fontSize: '0.72rem', mt: 0.5, lineHeight: 1.45 }}>
                {companyContact}
              </Typography>
            ) : null}
          </Box>
        ) : null}
      </Box>
    </Box>
  );
}

const PayslipContent = React.forwardRef<HTMLDivElement, Props>(function PayslipContent(
  { row, labels, companyInfo, showTitle = true, wide = false, forPdf = false },
  ref
) {
  const dayHours = parseMoney(row.day_ot_hour);
  const otRate = parseMoney(row.ot_rate);
  const otPayTotal = Math.floor(dayHours * otRate);

  const grossPay = parseMoney(row.sum_total);
  const pfEmp = parseMoney(row.pf_employee);
  const esicEmp = parseMoney(row.esic_employee);
  const tdsAmt = parseMoney(row.tds);
  const ptAmt = parseMoney(row.pt);
  const otherDeduct = Math.max(0, parseMoney(row.deduct_this_month) - (pfEmp + esicEmp + tdsAmt + ptAmt));
  const totalDeductions =
    parseMoney(row.deduct_this_month) > 0
      ? parseMoney(row.deduct_this_month)
      : pfEmp + esicEmp + tdsAmt + ptAmt + otherDeduct;
  const netPay = parseMoney(row.net_salary_payable);

  const dayOtLabel =
    dayHours > 0 ? `${labels.dayOt} (${formatOtHourDisplay(dayHours)}h)` : labels.dayOt;

  const companyName = companyInfo?.name || '—';
  const companyContact = [companyInfo?.address, companyInfo?.phone, companyInfo?.email]
    .filter((x) => !!String(x || '').trim())
    .join(' · ');

  const earningItems: LedgerLine[] = [
    { label: labels.basicSalary, value: money(row.basic_salary) },
    { label: labels.houseRentAllowance, value: money(row.house_rent_allowance) },
    { label: labels.otherAllowance, value: money(row.other_allowance) }
  ];
  if (dayHours > 0) earningItems.push({ label: dayOtLabel, value: money(otPayTotal), highlight: true });
  if (dayHours === 0 && otPayTotal === 0) {
    earningItems.push({ label: labels.dayOt, value: money(0), highlight: true });
  }
  earningItems.push({ label: labels.extraAllowance, value: money(row.transport_allowance), highlight: true });

  const deductionItems: LedgerLine[] = [
    { label: labels.pfEmployee, value: moneyFromField(row.pf_employee) },
    { label: labels.esicEmployee, value: moneyFromField(row.esic_employee) },
    { label: labels.pt, value: moneyFromField(row.pt) },
    { label: labels.tds, value: money(row.tds) }
  ];
  if (otherDeduct > 0) {
    deductionItems.push({ label: labels.deductMonth, value: money(otherDeduct) });
  }

  return (
    <Box
      ref={ref}
      sx={{
        bgcolor: forPdf ? '#FFFFFF' : 'bodyArea.main',
        color: 'text.primary',
        p: wide || forPdf ? 0 : { xs: 0, sm: 0.5 },
        width: wide || forPdf ? '100%' : undefined,
        maxWidth: wide || forPdf ? '100%' : 760,
        mx: wide || forPdf ? 0 : 'auto',
        boxSizing: 'border-box'
      }}
    >
      <Box sx={{ ...mvsBodyCardSx, overflow: 'hidden' }}>
        <PayslipHeader
          labels={labels}
          showTitle={showTitle}
          workingMonth={row.working_month || '—'}
          paidDays={String(row.days_worked || '—')}
          companyName={companyName}
          companyContact={companyContact}
          forPdf={forPdf}
        />

        <Box sx={{ px: { xs: 2, sm: 2.5 }, pb: 2.5, pt: 2.5 }}>
          {/* 직원 정보 — Body 테이블 인셋 */}
          <SectionHeading>{labels.employee}</SectionHeading>
          <Box sx={{ ...mvsBodyTableInsetSx, mb: 3, borderRadius: '14px', overflow: 'hidden' }}>
            <Box
              sx={{
                ...mvsBodyTableFrameSx,
                p: { xs: 1.5, sm: 2 },
                display: 'grid',
                gridTemplateColumns: forPdf ? '1fr 1fr' : { xs: '1fr', sm: '1fr 1fr' },
                columnGap: 3,
                rowGap: 0
              }}
            >
              <EmpField label={labels.workingMonth} value={row.working_month} />
              <EmpField label={labels.statementDate} value={statementDateFromPeriod(row.working_month)} />
              <EmpField label={labels.totalDaysInMonth} value={String(row.total_day_of_month || '—')} />
              <EmpField label={labels.paidDays} value={String(row.days_worked || '—')} />
              <EmpField
                label={labels.unpaidLeave}
                value={String(row.unpaid_leave || '0')}
                highlight
              />
              <EmpField label={labels.empId} value={row.emp_id} />
              <EmpField label={labels.name} value={row.employee_name} />
              <EmpField label={labels.designation} value={row.position} />
              <EmpField label={labels.email} value={row.employee_email} link />
              <EmpField label={labels.dateOfJoin} value={row.joining_date} />
              <EmpField label={labels.department} value={row.department} />
              <EmpField label={labels.account} value={row.bank_account} />
              <EmpField label={labels.bank} value={row.bank_name} />
              <EmpField label={labels.ifsc} value={row.ifsc} />
            </Box>
          </Box>

          {/* 지급 · 공제 — 합계 행 정렬 */}
          <SectionHeading>{labels.earningsAndDeductions}</SectionHeading>
          <EarningsDeductionsTable
            labels={labels}
            earningItems={earningItems}
            deductionItems={deductionItems}
            grossPay={grossPay}
            totalDeductions={totalDeductions}
            forPdf={forPdf}
          />

          {/* 실수령 — Body 내부 카드 */}
          <Box
            sx={{
              ...mvsInnerCardSx,
              mb: 2,
              border: '2px solid',
              borderColor: 'primary.light',
              bgcolor: 'primary.50',
              borderRadius: '16px',
              overflow: 'hidden'
            }}
          >
            <Typography sx={{ fontWeight: 700, color: 'primary.main', fontSize: '0.85rem', mb: 0.5 }}>
              {labels.netPay}
            </Typography>
            <Typography
              sx={{
                fontWeight: 700,
                fontSize: { xs: '1.65rem', sm: '1.9rem' },
                color: 'text.primary',
                fontVariantNumeric: 'tabular-nums',
                lineHeight: 1.15,
                mb: 1,
                letterSpacing: '-0.02em'
              }}
            >
              {money(netPay)}
            </Typography>
            <Typography sx={{ ...mvsPageDescriptionSx, color: 'success.dark', fontWeight: 600 }}>
              {labels.amountInWords}: {inrAmountInWords(netPay)}
            </Typography>
          </Box>

          <Typography variant="caption" sx={{ ...mvsPageDescriptionSx, display: 'block', textAlign: 'center' }}>
            {labels.autoGenerated}
          </Typography>
        </Box>
      </Box>
    </Box>
  );
});

export default PayslipContent;
